apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "weatherapi.fullname" . }}
  labels:
    {{- include "weatherapi.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "weatherapi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "weatherapi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP